### ISSUE TITLE
Swagger'ın Ayağa Kaldırılması

### ISSUE THREAD

**Issue by merve-aydin-safrantek** [hub-burgan-com-tr/bbt.endorsement#11]
- [ ] Swagger'ın Ayağa Kaldırılması

**Comment by mehmet-cokyasar-safrantek** [comment]
Added swagger documentation

**Comment by mehmet-cokyasar-safrantek** [comment]
Added swagger documentation

**Comment by merve-aydin-safrantek** [comment]
![image](https://user-images.githubusercontent.com/98387555/157008035-35d80773-2f55-44df-bb08-571020040198.png)

swagger servisleri ve açıklamaları yazıldı
