### ISSUE TITLE
Açılan Database Tablolarının Script'lerinin Hazırlanması

### ISSUE THREAD

**Issue by merve-aydin-safrantek** [hub-burgan-com-tr/bbt.endorsement#20]

**Comment by onur-bozkurt-safrantek** [comment]
@merve-aydin-safrantek hangi tablonun scripti ???

**Comment by mehmet-cokyasar-safrantek** [comment]
![2022-03-07 13_05_42-](https://user-images.githubusercontent.com/69903602/157010341-6e3b6f35-0f92-45cd-b0c3-baffedb3f4f8.png)
