### ISSUE TITLE
Form ile Emir Ekle - Update of Marvel Screens

### ISSUE THREAD

**Issue by gizem-unal-safrantek** [hub-burgan-com-tr/bbt.endorsement#32]
- [x] Entering reference information on the form ile emir ekle page.
- [x] Removing the form ile ekle from section Yeni onay oluştur - Belge ekle

**Comment by merve-aydin-safrantek** [comment]
Marvel güncelllendi.
https://marvelapp.com/prototype/5i77bia/screen/84942622

https://marvelapp.com/prototype/5i77bia/screen/84595599
