### ISSUE TITLE
Login sayfasının oluşturulması

### ISSUE THREAD

**Issue by merve-aydin-safrantek** [hub-burgan-com-tr/bbt.endorsement#8]
Müşteri TCKN/VKN :

- [ ] TCKN ile işlem yapılırsa;
- [ ] 11 haneli numerik alandır.
- [ ] Zorunludur.
- [ ] Format kontrolü yapılmalıdır. 1111111 gibi veri girişlerine izin verilmemelidir.
- [ ] Eksik veri girişi yapıldığında “İnternet bankacılığına giriş yapmak için, lütfen ilgili alana T.C. Kimlik numaranızı veya Vergi Kimlik Numaranızı yazın.” uyarısı verilmelidir.
- [ ] Veri girişi yapılmadığında “İnternet bankacılığına giriş yapmak için, lütfen ilgili alana T.C. Kimlik numaranızı veya Vergi Kimlik Numaranızı yazın.” uyarısı verilmelidir.
- [ ] VKN ile işlem yapılırsa;
- [ ] 10 haneli numerik alandır.
- [ ] Zorunludur.
- [ ] Eksik veri girişi yapıldığında “İnternet bankacılığına giriş yapmak için, lütfen ilgili alana T.C. Kimlik numaranızı veya Vergi Kimlik Numaranızı yazın.” uyarısı verilmelidir.
- [ ] Veri girişi yapılmadığında “İnternet bankacılığına giriş yapmak için, lütfen ilgili alana T.C. Kimlik numaranızı veya Vergi Kimlik Numaranızı yazın.” uyarısı verilmelidir.

Şifre :

- [ ] En az 6 haneli nümerik alandır.
- [ ] Zorunlu alandır.
- [ ] Eksik veri girişi yapıldığında “Lütfen en az 6 karakter olan şifrenizi giriniz.” uyarısı verilmelidir.
- [ ] Veri girişi yapılmadığında “Lütfen en az 6 karakter olan şifrenizi giriniz.” uyarısı verilmelidir.

Giriş Yap:

- [ ] Zorunlu alanlar doldurulduktan sonra Giriş Yap butonuna tıklanmalıdır.
- [ ] Müşteriye ait internet bankacılığına giriş yapılır.

https://marvelapp.com/prototype/5i77bia/screen/84570816

![image](https://user-images.githubusercontent.com/98387555/154255920-7e32b4e2-259e-4eb6-88db-2b1c8b5c1346.png)

**Comment by onur-bozkurt-safrantek** [comment]
Durum nedir? 19 gün önce iş açılmış?
